### ISSUE TITLE
Disassemble NPE

### ISSUE THREAD

**Issue by Naton1** [roscopeco/jasm#40]
catchType can be null to catch all exceptions (finally blocks) according to [the asm docs](https://asm.ow2.io/javadoc/org/objectweb/asm/MethodVisitor.html#visitTryCatchBlock(org.objectweb.asm.Label,org.objectweb.asm.Label,org.objectweb.asm.Label,java.lang.String))

```
java.lang.NullPointerException: Parameter specified as non-null is null: method com.roscopeco.jasm.JasmDisassemblingVisitor$JasmDisassemblingMethodVisitor.visitTryCatchBlock, parameter type
	at com.roscopeco.jasm.JasmDisassemblingVisitor$JasmDisassemblingMethodVisitor.visitTryCatchBlock(JasmDisassemblingVisitor.kt)
	at org.objectweb.asm.ClassReader.readCode(ClassReader.java:1857)
	at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1514)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:744)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:424)
	at com.roscopeco.jasm.JasmDisassembler.disassemble(JasmDisassembler.kt:42)
```

**Comment by roscopeco** [comment]
Good catch, thanks for reporting. Will get this fixed!
